export const additionalServicesStyles = {
  container: {
    px: '$4',
    pt: '$0',
    pb: '$6',
    '$md-px': '$6',
  } as const,
  card: {
    borderRadius: '$2xl',
    bg: '$white',
    p: '$6',
    borderWidth: 1,
    borderColor: '$borderLight100',
    shadowColor: '$black',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
    width: '100%',
  } as const,
  progressContainer: {
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
    alignItems: 'center' as const,
    mb: '$2',
  } as const,
  progressText: {
    fontSize: '$xs',
    color: '$textMutedForeground',
    fontWeight: '$medium',
  } as const,
  percentText: {
    fontSize: '$xs',
    color: '#833247ff',
    fontWeight: '$bold',
  } as const,
  progressBarTrack: {
    w: '$full',
    h: 4,
    bg: '$borderLight200',
    borderRadius: '$full',
    mb: '$6',
    overflow: 'hidden' as const,
  } as const,
  progressBarFill: (percent: number) => ({
    w: `${percent}%`,
    h: '100%',
    bg: '#833247ff',
  }) as const,
  tabBar: {
    flexDirection: 'row' as const,
    borderBottomWidth: 1,
    borderBottomColor: '$borderLight200',
    mb: '$6',
  } as const,
  tabItem: (isActive: boolean) => ({
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    pb: '$3',
    px: '$4',
    borderBottomWidth: 2,
    borderBottomColor: isActive ? '#833247ff' : 'transparent',
    cursor: 'pointer' as const,
  }) as const,
  tabText: (isActive: boolean) => ({
    fontSize: '$sm',
    fontWeight: isActive ? '$bold' : '$medium',
    color: isActive ? '#833247ff' : '$textMutedForeground',
    ml: '$2',
  }) as const,
  sectionTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '$textForeground',
    mb: '$1',
  } as const,
  sectionSubtitle: {
    fontSize: '$sm',
    color: '$textMutedForeground',
    mb: '$5',
  } as const,
  formRow: {
    flexDirection: 'column' as const,
    '$md-flexDirection': 'row' as const,
    space: 'lg' as const,
    mb: '$4',
  } as const,
  formCol: {
    flex: 1,
    space: 'xs' as const,
  } as const,
  labelContainer: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    mb: '$1.5',
  } as const,
  label: {
    fontSize: '$sm',
    fontWeight: '$semibold',
    color: '$textForeground',
  } as const,
  labelAsterisk: {
    color: '$red600',
    marginLeft: 2,
  } as const,
  input: {
    variant: 'outline' as const,
    size: 'md' as const,
    bg: '$white' as const,
    borderRadius: '$xl' as const,
    borderWidth: 1,
    borderColor: '$borderLight300' as const,
    px: '$3' as const,
    py: '$1' as const,
    boxShadow: 'none' as const,
    '$web-boxShadow': 'none' as const,
    '$focus': {
      borderColor: '#833247ff' as const,
      borderWidth: 1 as const,
      boxShadow: '0 0 0 2px rgba(131, 50, 71, 0.2)' as const,
      '$web-boxShadow': '0 0 0 2px rgba(131, 50, 71, 0.2)' as const,
    } as any,
  },
  select: {
    variant: 'outline' as const,
    size: 'md' as const,
    bg: '$white' as const,
    borderRadius: '$xl' as const,
    borderWidth: 1,
    borderColor: '$borderLight300' as const,
    boxShadow: 'none' as const,
    '$web-boxShadow': 'none' as const,
    '$focus': {
      borderColor: '#833247ff' as const,
      borderWidth: 1 as const,
      boxShadow: '0 0 0 2px rgba(131, 50, 71, 0.2)' as const,
      '$web-boxShadow': '0 0 0 2px rgba(131, 50, 71, 0.2)' as const,
    } as any,
  },
  pillContainer: {
    flexDirection: 'row' as const,
    space: 'sm' as const,
    flexWrap: 'wrap' as const,
    mt: '$1',
  } as const,
  pill: (isSelected: boolean) => ({
    px: '$6',
    py: '$3',
    borderRadius: '$xl',
    borderWidth: 1,
    borderColor: isSelected ? '#833247ff' : '$borderLight300',
    bg: isSelected ? '#833247ff' : '$white',
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    minWidth: 120,
    cursor: 'pointer' as const,
  }) as const,
  pillText: (isSelected: boolean) => ({
    fontSize: '$sm',
    fontWeight: '$semibold',
    color: isSelected ? '$white' : '$textMutedForeground',
  }) as const,
  textarea: {
    variant: 'outline' as const,
    size: 'md' as const,
    bg: '$white' as const,
    borderRadius: '$xl' as const,
    borderWidth: 1,
    borderColor: '$borderLight300' as const,
    px: '$3' as const,
    py: '$2' as const,
    minHeight: 80,
    boxShadow: 'none' as const,
    '$web-boxShadow': 'none' as const,
    '$focus': {
      borderColor: '#833247ff' as const,
      borderWidth: 1 as const,
      boxShadow: '0 0 0 2px rgba(131, 50, 71, 0.2)' as const,
      '$web-boxShadow': '0 0 0 2px rgba(131, 50, 71, 0.2)' as const,
    } as any,
  },
  timeInputIconContainer: {
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
    pr: '$2',
  } as const,
  infoBox: {
    borderLeftWidth: 4,
    borderLeftColor: '$info500',
    bg: '$info50',
    p: '$4',
    borderRadius: '$md',
    mb: '$5',
  } as const,
  infoTitleRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    mb: '$2',
  } as const,
  infoTitle: {
    fontSize: '$sm',
    fontWeight: '$bold',
    color: '$info700',
    ml: '$2',
  } as const,
  infoBullet: {
    flexDirection: 'row' as const,
    alignItems: 'flex-start' as const,
    mb: '$1.5',
    pl: '$2',
  } as const,
  infoBulletText: {
    fontSize: '$xs',
    color: '$info800',
    lineHeight: '$md',
  } as const,
  footer: {
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
    alignItems: 'center' as const,
    mt: '$6',
  } as const,
  prevBtn: (disabled: boolean) => ({
    variant: 'link' as const,
    opacity: disabled ? 0.4 : 1,
  }) as const,
  prevBtnText: {
    fontSize: '$sm',
    fontWeight: '$semibold',
    color: '$textMutedForeground',
    ml: '$1',
  } as const,
  rightActions: {
    flexDirection: 'row' as const,
    space: 'md' as const,
  } as const,
  saveDraftBtn: {
    variant: 'outline' as const,
    borderColor: '$borderLight300',
    bg: '$white',
    borderRadius: '$xl',
    px: '$5',
    py: '$2.5',
  } as const,
  saveDraftBtnText: {
    fontSize: '$sm',
    fontWeight: '$semibold',
    color: '$textForeground',
    ml: '$2',
  } as const,
  continueBtn: {
    bg: '#833247ff',
    borderRadius: '$xl',
    px: '$6',
    py: '$2.5',
  } as const,
  continueBtnText: {
    fontSize: '$sm',
    fontWeight: '$semibold',
    color: '$white',
    mr: '$2',
  } as const,
  publishBtn: {
    bg: '$success600',
    borderRadius: '$xl',
    px: '$6',
    py: '$2.5',
  } as const,
  publishBtnText: {
    fontSize: '$sm',
    fontWeight: '$semibold',
    color: '$white',
    mr: '$2',
  } as const,
  reviewSectionCard: {
    borderWidth: 1,
    borderColor: '$borderLight200',
    borderRadius: '$xl',
    p: '$4',
    mb: '$4',
  } as const,
  reviewRow: {
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
    borderBottomWidth: 1,
    borderBottomColor: '$borderLight100',
    py: '$2.5',
  } as const,
  reviewLabel: {
    fontSize: '$sm',
    color: '$textMutedForeground',
    flex: 1,
  } as const,
  reviewValue: {
    fontSize: '$sm',
    fontWeight: '$semibold',
    color: '$textForeground',
    flex: 2,
    textAlign: 'right' as const,
  } as const,
} as const;
