export const assetStyles = {
  input: {
    variant: 'outline' as const,
    size: 'md' as const,
    bg: '$white' as const,
    borderRadius: '$xl' as const,
    borderWidth: 1,
    borderColor: '$borderLight300' as const,
    px: '$3' as const,
    py: '$1' as const,
    boxShadow: 'none' as const,
    '$web-boxShadow': 'none' as const,
    '$focus': {
      borderColor: '#833247ff' as const,
      borderWidth: 1 as const,
      boxShadow: '0 0 0 2px rgba(131, 50, 71, 0.2)' as const,
      '$web-boxShadow': '0 0 0 2px rgba(131, 50, 71, 0.2)' as const,
    } as any,
  },
  select: {
    variant: 'outline' as const,
    size: 'md' as const,
    bg: '$white' as const,
    borderRadius: '$xl' as const,
    borderWidth: 1,
    borderColor: '$borderLight300' as const,
    boxShadow: 'none' as const,
    '$web-boxShadow': 'none' as const,
    '$focus': {
      borderColor: '#833247ff' as const,
      borderWidth: 1 as const,
      boxShadow: '0 0 0 2px rgba(131, 50, 71, 0.2)' as const,
      '$web-boxShadow': '0 0 0 2px rgba(131, 50, 71, 0.2)' as const,
    } as any,
  },
} as const;
