export default {
  container: {
    px: '$4',
    py: '$6',
    '$md-px': '$6',
  },
  title: {
    fontSize: 24,
    fontWeight: '700',
  },
  pressable: {
    flex: 1,
    minWidth: 280,
    bg: '$white',
    p: '$8',
    borderRadius: '$2xl',
    borderWidth: 2,
    borderColor: '$borderLight100',
    '$hover-borderColor': '$primary500',
    '$hover-shadowColor': '$shadowColor',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 2,
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    transition: 'all 0.2s ease-in-out',
  },
};
