export default {
  container: {
    px: '$4',
    py: '$6',
    '$md-px': '$6',
  } as const,
  title: {
    fontSize: 24,
    fontWeight: '700',
  } as const,
  cardContainer: {
    bg: '$white',
    borderRadius: '$2xl',
    borderWidth: 1,
    borderColor: '$borderColor',
    p: '$5',
    width: '100%',
    marginBottom: '$4',
    sx: {
      ':hover': {
        shadowColor: '$black',
        shadowOffset: { width: 0, height: 4 } as const,
        shadowOpacity: 0.06,
        shadowRadius: 8,
        elevation: 3,
      },
    },
  } as const,
  tabBarBox: {
    bg: '$white',
    borderBottomWidth: 1,
    borderBottomColor: '$borderLight100',
  } as const,
  cardHeaderPressable: {
    px: '$5' as const,
    py: '$5' as const,
    width: '100%' as const,
  } as const,
  modalFooterSkipButton: {
    variant: 'outline' as any,
    borderColor: '$borderColor',
    bg: '$white',
    borderRadius: '$lg',
    px: '$5',
    py: '$2.5',
  } as const,
  modalFooterSkipButtonText: {
    color: '$textForegroundColor',
    fontSize: '$sm',
    fontWeight: '$semibold',
  } as const,
  modalFooterConfirmButton: {
    bg: '$success600',
    borderRadius: '$lg',
    px: '$5',
    py: '$2.5',
    sx: {
      ':hover': { bg: '$success700' } as const,
      ':active': { bg: '$success700' } as const,
    } as const,
  } as const,
  modalFooterConfirmButtonText: {
    color: '$white',
    fontSize: '$sm',
    fontWeight: '$semibold',
  } as const,
  modalParticipantCard: {
    borderWidth: 1,
    borderColor: '$borderColor',
    borderRadius: '$xl',
    p: '$3.5',
    bg: '$white',
    width: '100%' as const,
  } as const,
  modalParticipantNumberText: {
    fontSize: '$xs' as const,
    color: '$textMuted' as const,
    width: 24,
    fontWeight: '$medium' as const,
  } as const,
  modalParticipantNameText: {
    fontSize: '$sm' as const,
    fontWeight: '$normal' as const,
    color: '$textPrimary' as const,
  } as const,
  modalParticipantLcText: {
    fontSize: '$xs' as const,
    color: '$textMuted' as const,
  } as const,
  modalCountText: {
    fontSize: '$sm' as const,
    fontWeight: '$semibold' as const,
    color: '$textMuted' as const,
  } as const,
  modalMarkAllText: {
    fontSize: '$xs' as const,
    color: '$blue500' as const,
    fontWeight: '$medium' as const,
  } as const,
  modalClearAllText: {
    fontSize: '$xs' as const,
    color: '$textMuted' as const,
    fontWeight: '$medium' as const,
  } as const,
  modalDividerText: {
    fontSize: '$xs' as const,
    color: '$textMuted' as const,
  } as const,
  modalScrollView: {
    maxHeight: 320,
    width: '100%' as const,
  } as const,
  cardRightActionStack: {
    space: 'sm' as const,
    width: '100%' as const,
    '$md-width': 160,
    justifyContent: 'center' as const,
    alignSelf: 'stretch' as const,
  } as const,
  inKindBadgeContainer: {
    bg: '$success50' as const,
    borderWidth: 0,
    px: '$2' as const,
    py: '$0.5' as const,
    borderRadius: '$full' as const,
  } as const,
  inKindBadgeText: {
    fontSize: '$xs' as const,
    color: '$success600' as const,
    fontWeight: '$semibold' as const,
    textTransform: 'none' as const,
  } as const,
  viewRequestsBtn: {
    borderWidth: 1,
    borderColor: '$borderColor',
    bg: '$white',
    px: '$4',
    py: '$2',
    borderRadius: '$lg',
    alignItems: 'center' as const,
    sx: {
      ':hover': { bg: '$hoverBackground' } as const,
      ':active': { bg: '$hoverBackground' } as const,
    } as const,
  } as const,
  copyOfferingBtn: {
    borderWidth: 1,
    borderColor: '$primary600',
    bg: '$primary300',
    px: '$4',
    py: '$2',
    borderRadius: '$lg',
    alignItems: 'center' as const,
    sx: {
      ':hover': { bg: '$primary300' } as const,
      ':active': { bg: '$primary300' } as const,
    } as const,
  } as const,
  completeBtn: {
    bg: '$success600',
    px: '$4',
    py: '$2',
    borderRadius: '$lg',
    alignItems: 'center' as const,
    sx: {
      ':hover': { bg: '$success700' } as const,
      ':active': { bg: '$success700' } as const,
    } as const,
  } as const,
  uploadMaterialBtn: {
    borderWidth: 1,
    borderColor: '$borderColor',
    bg: '$white',
    px: '$3',
    py: '$1.5',
    borderRadius: '$lg',
    sx: {
      ':hover': { backgroundColor: '$hoverBackground' } as const,
    } as const,
  } as const,
  sessionCompleteBtn: {
    bg: '$success600',
    px: '$4',
    py: '$2',
    borderRadius: '$lg',
    sx: {
      ':hover': { bg: '$success700' } as const,
      ':active': { bg: '$success700' } as const,
    } as const,
  } as const,
  copySessionBox: (isHovered: boolean) => ({
    borderWidth: 1,
    borderColor: '$borderColor',
    bg: isHovered ? '$hoverBackground' : '$white',
    px: '$3.5',
    py: '$2',
    borderRadius: '$lg',
  }) as const,
  outlineActionBtn: {
    height: 32,
    px: '$3',
    py: '$0',
    borderRadius: '15',
    borderWidth: 1,
    borderColor: '$borderColor',
    bg: '$white',
    alignItems: 'center',
    justifyContent: 'center',
  },
  outlineActionBtnText: {
    fontSize: '$xs',
    lineHeight: 12,
    fontWeight: '200',
    color: '$textPrimary',
  },
  detailsBtn: {
    height: 32,
    px: '$3',
    py: '$0',
    borderRadius: '15',
    bg: '$primary500',
    alignItems: 'center',
    justifyContent: 'center',
  },

  detailsBtnText: {
    fontSize: '$xs',
    lineHeight: 12,
    fontWeight: '200',
    color: '$white',
  },
  completeActionBtn: {
    height: 32,
    px: '$3',
    py: '$0',
    borderRadius: '15',
    bg: '$success600',
    alignItems: 'center',
    justifyContent: 'center',
  },
  completeActionBtnText: {
    fontSize: '$xs',
    lineHeight: 12,
    fontWeight: '$normal',
    color: '$white',
  },
  attendanceBox: {
    bg: '$white' as const,
    borderWidth: 1,
    borderColor: '$borderColor',
    p: '$3.5',
    borderRadius: '$lg',
    width: '100%' as const,
  } as const,
  materialFileCard: {
    borderWidth: 1,
    borderColor: '$borderColor',
    borderRadius: '$lg',
    py: '$2.5' as const,
    px: '$3.5' as const,
    bg: '$white' as const,
    width: '100%' as const,
  } as const,
  resourceCard: {
    borderWidth: 1,
    borderColor: '$borderColor',
    borderRadius: '$lg',
    py: '$2.5' as const,
    px: '$3.5' as const,
    bg: '$white' as const,
    width: '100%' as const,
  } as const,
  resourceFileNameText: {
    fontSize: '$xs' as const,
    fontWeight: '$normal' as const,
    color: '$textPrimary' as const,
  } as const,
  downloadLinkText: {
    fontSize: '$xs' as const,
    fontWeight: '$medium' as const,
    color: '$blue600' as const,
  } as const,
  notesBox: {
    bg: '$hoverBackground' as const,
    borderWidth: 1,
    borderColor: '$light100' as const,
    px: '$4',
    py: '$2.5',
    borderRadius: '$lg',
    width: '100%' as const,
    marginTop: '$1' as const,
  } as const,
  notesText: {
    fontSize: '$sm',
    color: '$textMuted',
    lineHeight: '$lg',
    numberOfLines: 2,
    ellipsizeMode: 'tail',
  } as const,
  cardTitleText: {
    fontSize: '$md' as const,
    fontWeight: '$bold' as const,
    color: '$textForegroundColor' as const,
  } as const,
  cardHeaderTitleText: {
    fontSize: '$md' as const,
    fontWeight: '$bold' as const,
    color: '$textPrimary' as const,
  } as const,
  cardDescriptionText: {
    fontSize: '$xs' as const,
    color: '$textSecondary' as const,
    lineHeight: '$md' as const,
  } as const,
  cardMetaText: {
    fontSize: 11 as const,
    color: '$textSecondary' as const,
  } as const,
  cardMetaSmText: {
    fontSize: '$xs' as const,
    color: '$textSecondary' as const,
    fontWeight: '$normal' as const,
  } as const,
  cardLocationValueText: {
    fontSize: '$xs' as const,
    color: '$textPrimary' as const,
    fontWeight: '$normal' as const,
  } as const,
  cardRequestedByText: {
    fontSize: '$xs' as const,
    color: '$textSecondary' as const,
    fontWeight: '$normal' as const,
    flex: 1,
  } as const,
  cardRequestedByOrgText: {
    fontSize: '$xs' as const,
    color: '$textPrimary' as const,
    fontWeight: '$normal' as const,
  } as const,
  cardRequestedByProvinceText: {
    fontSize: '$xs' as const,
    color: '$textSecondary' as const,
    fontWeight: '$normal' as const,
  } as const,
  cardSectionTitleText: {
    fontSize: '$sm' as const,
    fontWeight: '$bold' as const,
    color: '$textPrimary' as const,
    marginTop: '$1' as const,
  } as const,
  cardValueBoldText: {
    fontSize: '$sm' as const,
    fontWeight: '$bold' as const,
    color: '$textPrimary' as const,
  } as const,
  cardValueBoldSmText: {
    fontSize: '$xs' as const,
    fontWeight: '$semibold' as const,
    color: '$textPrimary' as const,
  } as const,
  cardSuccessBoldText: {
    fontSize: '$xs' as const,
    fontWeight: '$bold' as const,
    color: '$success600' as const,
  } as const,
  cardPrimaryLinkText: {
    fontSize: '$xs' as const,
    color: '$blue600' as const,
    textDecorationLine: 'underline' as const,
  } as const,
  cardBtnSecondaryText: {
    fontSize: '$xs' as const,
    fontWeight: '$normal' as const,
    color: '$textSecondary' as const,
  } as const,
  cardBtnPrimaryText: {
    fontSize: '$xs' as const,
    fontWeight: '$medium' as const,
    color: '$textPrimary' as const,
  } as const,
  cardBtnWhiteText: {
    fontSize: '$xs' as const,
    fontWeight: '$normal' as const,
    color: '$white' as const,
  } as const,
  cardBtnWhiteSemiboldText: {
    fontSize: '$xs' as const,
    fontWeight: '$semibold' as const,
    color: '$white' as const,
  } as const,
  badgeContainer: (bg: string, border?: string) => ({
    bg,
    borderWidth: border ? 1 : 0,
    borderColor: border || 'transparent',
    paddingTop: 2 as const,
    paddingBottom: 2 as const,
    paddingLeft: 10 as const,
    paddingRight: 10 as const,
    borderRadius: '$full' as const,
  }),
  badgeText: (color: string) => ({
    fontSize: 11 as const,
    color,
    fontWeight: '$medium' as const,
    textTransform: 'none' as const,
  }),
  deliveryBadgeContainer: (bg: string, border: string) => ({
    bg,
    borderWidth: 1,
    borderColor: border,
    paddingTop: 2 as const,
    paddingBottom: 2 as const,
    paddingLeft: 8 as const,
    paddingRight: 8 as const,
    borderRadius: '$full' as const,
  }),
  deliveryBadgeText: (color: string) => ({
    fontSize: 11 as const,
    color,
    fontWeight: '$medium' as const,
    textTransform: 'none' as const,
  }),
  contentContainer: {
    space: 'md',
    width: '100%',
  } as const,
  tabTextProps: {
    fontSize: '$sm',
  } as const,
  tabButtonContainer: {
    paddingHorizontal: '$5',
  } as const,
  filterContainer: {
    py: '$4' as const,
    px: '$6' as const,
    mb: '$2' as const,
    mt: '$0' as const,
  } as const,
  filterInputProps: {
    bg: 'transparent' as const,
    borderColor: '$borderColor' as const,
    size: 'sm' as const,
  } as const,
  cardHeaderHStack: {
    flexDirection: 'column' as const,
    '$md-flexDirection': 'row' as const,
    justifyContent: 'space-between' as const,
    alignItems: 'stretch' as const,
    '$md-alignItems': 'center' as const,
    space: 'lg' as const,
  } as const,
  listContainer: {
    width: '100%' as const,
  } as const,
  cardLeftVStack: {
    flex: 1,
    space: 'sm' as const,
  } as const,
  titleRowHStack: {
    space: 'sm' as const,
    alignItems: 'center' as const,
    flexWrap: 'wrap' as const,
  } as const,
  badgeContentHStack: {
    space: 'sm' as const,
    alignItems: 'center' as const,
  } as const,
  metaRowHStack: {
    space: 'md' as const,
    alignItems: 'center' as const,
    flexWrap: 'wrap' as const,
  } as const,
  metaItemHStack: {
    space: 'xs' as const,
    alignItems: 'center' as const,
  } as const,
  trainingMetaItemHStack: {
    space: 'xs' as const,
    alignItems: 'center' as const,
  } as const,
  pressableInnerHStack: {
    space: 'xs' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  } as const,
  cardFullVStack: {
    space: 'md' as const,
    width: '100%' as const,
  } as const,
  headerTopHStack: {
    justifyContent: 'space-between' as const,
    alignItems: 'center' as const,
    width: '100%' as const,
  } as const,
  headerTitleBadgeHStack: {
    space: 'sm' as const,
    alignItems: 'center' as const,
    flex: 1,
    flexWrap: 'wrap' as const,
  } as const,
  headerMetaHStack: {
    space: 'xl' as const,
    alignItems: 'center' as const,
    flexWrap: 'wrap' as const,
    width: '100%' as const,
    marginTop: '$1' as const,
  } as const,
  requestedByRowHStack: {
    justifyContent: 'space-between' as const,
    alignItems: 'center' as const,
    flexWrap: 'wrap' as const,
    space: 'sm' as const,
    width: '100%' as const,
    marginTop: '$1' as const,
  } as const,
  expandedContentVStack: {
    width: '100%' as const,
    space: 'md' as const,
    bg: '$hoverBackground' as const,
    borderTopWidth: 1,
    borderTopColor: '$borderColor' as const,
    p: '$4' as const,
    // marginTop: '$1' as const,
    borderRadius: '$xl' as const,
  } as const,
  expandedInnerVStack: {
    space: 'md' as const,
    width: '100%' as const,
  } as const,
  sectionVStack: {
    space: 'sm' as const,
    width: '100%' as const,
  } as const,
  sectionSmVStack: {
    space: 'sm' as const,
    width: '100%' as const,
  } as const,
  virtualLinkHStack: {
    space: 'xs' as const,
    alignItems: 'center' as const,
    flexWrap: 'wrap' as const,
    width: '100%' as const,
  } as const,
  attendanceRowHStack: {
    justifyContent: 'flex-start' as const,
    alignItems: 'flex-start' as const,
    space: '2xl' as const,
    flexWrap: 'wrap' as const,
    width: '100%' as const,
    marginTop: '$2' as const,
  } as const,
  attendanceItemVStack: {
    space: 'xs' as const,
    minWidth: 160,
    marginTop: '$1' as const,
  } as const,
  materialsHeaderHStack: {
    justifyContent: 'space-between' as const,
    alignItems: 'center' as const,
    width: '100%' as const,
  } as const,
  fileCardOuterHStack: {
    justifyContent: 'space-between' as const,
    alignItems: 'center' as const,
    space: 'sm' as const,
    width: '100%' as const,
  } as const,
  fileCardInnerHStack: {
    space: 'sm' as const,
    alignItems: 'center' as const,
    flex: 1,
  } as const,
  fileIconBox: {
    bg: '$primary100' as const,
    p: '$2.5' as const,
    borderRadius: '$lg' as const,
  } as const,
  fileTextVStack: {
    flex: 1,
    space: 'xs' as const,
  } as const,
  filesListVStack: {
    space: 'sm' as const,
    width: '100%' as const,
  } as const,
  sessionCompleteHStack: {
    justifyContent: 'flex-end' as const,
    width: '100%' as const,
    pt: '$2' as const,
  } as const,
  cardAccordionContainer: {
    p: '$5' as const,
    overflow: 'hidden' as const,
  } as const,
  dividerStyle: {
    bg: '$borderColor' as const,
  } as const,
  iconPressablePadding: {
    p: '$1' as const,
  },
  cardMetaIconProps: {
    size: 13,
    color: '$textSecondary' as const,
  },
  cardCopyIconProps: {
    size: 16,
    color: '$textPrimary',
  },
  cardWhiteIconProps: {
    size: 16,
    color: '$white',
  },
  badgeIconProps: (color: string) => ({
    size: 11,
    color,
  }) as const,
  cardChevronIconProps: {
    size: 16,
    color: '$textMuted' as const,
  },
  cardPrimaryIconProps: {
    size: 13,
    color: '$blue600' as const,
  },
  cardSuccessIconProps: {
    size: 13,
    color: '$success600' as const,
  },
  cardFileTextIconProps: {
    size: 15,
    color: '$blue600' as const,
  },
  modalFooterHStack: {
    space: 'md' as const,
    justifyContent: 'flex-end' as const,
    width: '100%' as const,
  } as const,
  modalButtonIconProps: {
    mr: '$1' as const,
    color: '$white' as const,
    size: 16,
  } as const,
  modalTopBarHStack: {
    justifyContent: 'space-between' as const,
    alignItems: 'center' as const,
    width: '100%' as const,
  } as const,
  modalActionsHStack: {
    space: 'sm' as const,
    alignItems: 'center' as const,
  } as const,
  modalParticipantInnerHStack: {
    space: 'md' as const,
    alignItems: 'center' as const,
    width: '100%' as const,
  } as const,
  modalCheckboxIndicator: (isChecked: boolean) => ({
    borderColor: isChecked ? '$primary500' : '$borderColor',
    bg: isChecked ? '$primary500' : 'transparent',
    borderRadius: '$md' as const,
  }),
  pressable: {
    flex: 1,
    minWidth: 280,
    bg: '$white',
    p: '$8',
    borderRadius: '$2xl',
    borderWidth: 2,
    borderColor: '$borderLight100',
    '$hover-borderColor': '$primary500',
    '$hover-shadowColor': '$shadowColor',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 2,
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    transition: 'all 0.2s ease-in-out',
  },
};