export default {
  container: {
    px: '$4',
    py: '$6',
    '$md-px': '$6',
  } as const,
  title: {
    fontSize: 24,
    fontWeight: '700',
  } as const,
  cardContainer: {
    bg: '$white',
    borderRadius: '$2xl',
    borderWidth: 1,
    borderColor: '$borderLight200',
    p: '$5',
    shadowColor: '$black',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 12,
    elevation: 3,
    width: '100%',
  } as const,
  detailBox: {
    bg: '#F8FAFC',
    borderRadius: '$lg',
    px: '$5',
    py: '$4',
    mb: '$4',
  } as const,
  overdueBadge: {
    bg: '$red50',
    borderColor: '$red300',
    borderWidth: 1,
    px: '$3',
    py: '$1',
    borderRadius: '$full',
  } as const,
  pendingBadge: {
    bg: '$yellow50',
    borderColor: '$yellow200',
    borderWidth: 1,
    px: '$3',
    py: '$1',
    borderRadius: '$full',
  } as const,
  requestInfoBtn: {
    borderWidth: 1,
    borderColor: '$borderLight200',
    bg: '$white',
    px: '$4',
    py: '$2',
    borderRadius: '$lg',
    sx: { ':active': { bg: '$backgroundLight50' } },
  } as const,
  declineBtn: {
    borderWidth: 1,
    borderColor: '$red200',
    bg: '$white',
    px: '$4',
    py: '$2',
    borderRadius: '$lg',
    sx: { ':active': { bg: '$red50' } },
  } as const,
  acceptBtn: {
    bg: '$success600',
    px: '$4.5',
    py: '$2',
    borderRadius: '$lg',
    shadowColor: '$green800',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 2,
    sx: { ':active': { bg: '$green700' } },
  } as const,
  summaryBox: {
    bg: '$blue50',
    borderWidth: 1,
    borderColor: '$blue200',
    p: '$4',
    borderRadius: '$xl',
  } as const,
  inputStyle: {
    borderWidth: 1,
    borderColor: '$borderLight300',
    borderRadius: '$lg',
    bg: '$white',
    px: '$3',
    py: '$2',
    '$focus-borderColor': '$primary500',
  } as const,
  textareaStyle: {
    borderWidth: 1,
    borderColor: '$borderLight300',
    borderRadius: '$lg',
    bg: '$white',
    h: 85,
    p: '$1',
    '$focus-borderColor': '$primary500',
  } as const,
  modalCancelBtn: {
    borderWidth: 1,
    borderColor: '$borderLight200',
    bg: '$white',
    px: '$4',
    py: '$2.5',
    borderRadius: '$lg',
    sx: { ':active': { bg: '$backgroundLight50' } },
  } as const,
  modalConfirmBtn: {
    bg: '$success600',
    px: '$5',
    py: '$2.5',
    borderRadius: '$lg',
    shadowColor: '$green800',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 2,
    sx: { ':active': { bg: '$green700' } },
  } as const,
  tabsHeader: {
    borderBottomWidth: 1,
    borderBottomColor: '$borderLight200',
    alignItems: 'center',
    space: 'sm',
  } as const,
  filterContainer: {
    borderWidth: 0,
    bg: 'transparent',
    p: 0,
    mt: 0,
    mb: '$2',
    shadowColor: 'transparent',
    elevation: 0,
  } as const,
  pendingHeaderBadge: {
    bg: '$warning600',
    px: '$3',
    py: '$0.5',
    borderRadius: '$full',
  } as const,
  overdueHeaderBadge: {
    bg: '$error600',
    px: '$3',
    py: '$0.5',
    borderRadius: '$full',
  } as const,
};