export default {
  container: {
    px: '$4',
    pt: '$0',
    pb: '$6',
    '$md-px': '$6',
  } as const,
  contentContainer: {
    space: 'lg',
    width: '100%',
  } as const,
  uploadButtonProps: {
    bg: '$primary500',
    px: '$4',
    py: '$2.5',
    borderRadius: '$xl',
    sx: { ':active': { bg: '$primary600' } },
  } as const,
  filterBoxContainerProps: {
    p: '$4',
    mt: '$1',
  } as const,

  // Merged Component Styles
  statsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: '-$2',
    mt: '$4',
    mb: '-$4',
    width: '100%',
  } as const,
  statCardContainer: {
    flex: 1,
    bg: '$white',
    borderRadius: '$2xl',
    borderWidth: 1,
    borderColor: '$borderLight200',
    p: '$5',
    minWidth: 200,
    marginHorizontal: '$2',
    marginBottom: '$4',
    shadowColor: '$black',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 10,
    elevation: 2,
  } as const,
  statCardContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
  } as const,
  statTextCol: {
    space: 'xs',
    flex: 1,
  } as const,
  statTitleText: {
    fontSize: '$sm',
    fontWeight: '$medium',
    color: '$textMutedForeground',
    lineHeight: '$sm',
  } as const,
  statCountText: {
    fontSize: '$2xl',
    fontWeight: '$bold',
    color: '$textPrimary',
  } as const,
  statIconBox: {
    width: 44,
    height: 44,
    borderRadius: '$xl',
    borderWidth: 1.5,
    alignItems: 'center',
    justifyContent: 'center',
  } as const,
  cardsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: '-$3',
    width: '100%',
  } as const,
  cardWrapper: {
    width: '100%',
    '$md-width': '33.33%',
    px: '$3',
    mb: '$6',
  } as const,
  materialCard: {
    bg: '$white',
    borderRadius: '$2xl',
    borderWidth: 1,
    borderColor: '$borderLight200',
    p: '$5',
    shadowColor: '$black',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 12,
    elevation: 3,
    height: '100%',
    justifyContent: 'space-between',
  } as const,
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    mb: '$3',
    width: '100%',
  } as const,
  cardHeaderIconBox: {
    width: 44,
    height: 44,
    borderRadius: '$xl',
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  } as const,
  categoryBadgeCard: {
    flexDirection: 'row',
    alignItems: 'center',
    px: '$2.5',
    py: '$0.5',
    borderRadius: '$full',
    borderWidth: 1,
    borderColor: '$borderLight300',
    bg: '$backgroundLight50',
    alignSelf: 'flex-start',
  } as const,
  categoryBadgeTextCard: {
    fontSize: '$xs',
    fontWeight: '$medium',
    color: '$textSecondary',
  } as const,
  cardTitle: {
    fontSize: '$md',
    fontWeight: '$bold',
    color: '$textPrimary',
    mt: '$1',
  } as const,
  cardDescription: {
    fontSize: '$sm',
    color: '$textSecondary',
    lineHeight: '$md',
    mb: '$4',
  } as const,
  fileInfoBox: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    bg: '$backgroundLight50',
    borderRadius: '$lg',
    px: '$3.5',
    py: '$2.5',
    mb: '$3',
    width: '100%',
  } as const,
  fileInfoLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    space: 'xs',
    flex: 1,
  } as const,
  fileNameText: {
    fontSize: '$xs',
    color: '$textPrimary',
    fontWeight: '$medium',
    flex: 1,
  } as const,
  fileSizeText: {
    fontSize: '$xs',
    color: '$textSecondary',
  } as const,
  linkedOfferingBox: {
    flexDirection: 'row',
    alignItems: 'center',
    space: 'xs',
    bg: '$blue50',
    borderRadius: '$lg',
    px: '$3.5',
    py: '$2.5',
    mb: '$4',
  } as const,
  linkedOfferingText: {
    fontSize: '$xs',
    fontWeight: '$semibold',
    color: '$blue700',
    flex: 1,
  } as const,
  metaRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    mb: '$5',
    borderTopWidth: 1,
    borderTopColor: '$borderLight100',
    pt: '$3.5',
  } as const,
  metaItemText: {
    fontSize: '$xs',
    color: '$textSecondary',
  } as const,
  downloadsText: {
    fontSize: '$xs',
    color: '$success700',
    fontWeight: '$semibold',
  } as const,
  downloadsBox: {
    flexDirection: 'row',
    alignItems: 'center',
    space: 'xs',
  } as const,
  cardFooterActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    space: 'xs',
    width: '100%',
  } as const,
  previewBtn: {
    borderWidth: 1,
    borderColor: '$borderLight200',
    bg: '$white',
    px: '$3',
    py: '$2',
    borderRadius: '$lg',
    sx: { ':active': { bg: '$backgroundLight50' } },
  } as const,
  previewBtnText: {
    fontSize: '$xs',
    fontWeight: '$semibold',
    color: '$textPrimary',
  } as const,
  deleteBtn: {
    borderWidth: 1,
    borderColor: '$red200',
    bg: '$white',
    p: '$2',
    borderRadius: '$lg',
    alignItems: 'center',
    justifyContent: 'center',
    sx: { ':active': { bg: '$red50' } },
  } as const,
  downloadBtn: {
    bg: '$success600',
    px: '$4',
    py: '$2',
    borderRadius: '$lg',
    sx: { ':active': { bg: '$success700' } },
  } as const,
  downloadBtnText: {
    fontSize: '$xs',
    fontWeight: '$bold',
    color: '$white',
  } as const,
  uploadModalBtn: {
    bg: '$primary500',
    px: '$4',
    py: '$2.5',
    borderRadius: '$xl',
    sx: { ':active': { bg: '$primary600' } },
  } as const,
  formInputGroup: {
    space: 'xs',
    width: '100%',
  } as const,
  formLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    space: 'xs',
  } as const,
  formLabelText: {
    fontSize: '$sm',
    fontWeight: '$semibold',
    color: '$textPrimary',
  } as const,
  formRequiredText: {
    color: '$red600',
    fontSize: '$sm',
    fontWeight: '$bold',
  } as const,
  formInput: {
    borderWidth: 1,
    borderColor: '$borderLight300',
    borderRadius: '$lg',
    bg: '$white',
    px: '$3',
    height: 44,
    justifyContent: 'center',
    width: '100%',
    '$focus-borderColor': '$primary500',
  } as const,
  formTextarea: {
    borderWidth: 1,
    borderColor: '$borderLight300',
    borderRadius: '$lg',
    bg: '$white',
    px: '$3',
    py: '$2',
    height: 90,
    width: '100%',
    '$focus-borderColor': '$primary500',
  } as const,
  selectTrigger: {
    borderWidth: 1,
    borderColor: '$borderLight300',
    borderRadius: '$lg',
    bg: '$white',
    px: '$3',
    height: 44,
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    '$focus-borderColor': '$primary500',
  } as const,
  selectInputProps: {
    fontSize: '$sm',
    color: '$textPrimary',
  } as const,
  formInputField: {
    fontSize: '$sm',
    color: '$textPrimary',
  } as const,
  errorMsgBox: {
    bg: '$red50',
    borderWidth: 1,
    borderColor: '$red200',
    p: '$3',
    borderRadius: '$lg',
  } as const,
  errorMsgText: {
    color: '$red700',
    fontSize: '$sm',
    fontWeight: '$semibold',
  } as const,
  previewDetailsBox: {
    width: '100%',
    mb: '$2',
  } as const,
  previewPurposeTitle: {
    fontSize: '$xs',
    fontWeight: '$bold',
    color: '$textSecondary',
    textTransform: 'uppercase',
    letterSpacing: '$sm',
    mb: '$1',
  } as const,
  previewPurposeValue: {
    fontSize: '$sm',
    fontWeight: '$bold',
    color: '$textPrimary',
    mb: '$2',
  } as const,
  previewPurposeDesc: {
    fontSize: '$sm',
    color: '$textSecondary',
    lineHeight: '$md',
  } as const,
  previewMetaGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: '-$2',
    mt: '$2',
  } as const,
  previewGridItem: {
    width: '50%',
    px: '$2',
    mb: '$3',
  } as const,
  previewGridLabel: {
    fontSize: '$xs',
    color: '$textSecondary',
    mb: '$0.5',
  } as const,
  previewGridValue: {
    fontSize: '$sm',
    fontWeight: '$bold',
    color: '$textPrimary',
  } as const,
  modalHeaderProps: {
    borderBottomWidth: 1,
    borderBottomColor: '$borderLight200',
    pb: '$4',
  } as const,
  modalCancelBtn: {
    borderWidth: 1,
    borderColor: '$borderLight300',
    bg: '$white',
    px: '$5',
    py: '$2',
    borderRadius: '$lg',
    sx: { ':active': { bg: '$backgroundLight50' } },
  } as const,
  modalCancelBtnText: {
    fontSize: '$sm',
    fontWeight: '$bold',
    color: '$textDark700',
  } as const,
  modalConfirmBtn: {
    bg: '$primary500',
    px: '$5',
    py: '$2',
    borderRadius: '$lg',
    sx: { ':active': { bg: '$primary600' } },
  } as const,
  modalConfirmBtnText: {
    fontSize: '$sm',
    fontWeight: '$bold',
    color: '$white',
  } as const,
  modalDownloadBtn: {
    bg: '$success600',
    px: '$5',
    py: '$2',
    borderRadius: '$lg',
    sx: { ':active': { bg: '$success700' } },
  } as const,
  modalDownloadBtnText: {
    fontSize: '$sm',
    fontWeight: '$bold',
    color: '$white',
  } as const,
  modalDeleteBtn: {
    bg: '$red600',
    px: '$5',
    py: '$2',
    borderRadius: '$lg',
    sx: { ':active': { bg: '$red700' } },
  } as const,
  modalDeleteBtnText: {
    fontSize: '$sm',
    fontWeight: '$bold',
    color: '$white',
  } as const,
  modalDescriptionText: {
    fontSize: '$sm',
    color: '$textSecondary',
    lineHeight: '$md',
    py: '$2',
  } as const,
  previewHeaderTag: {
    borderWidth: 1,
    px: '$2.5',
    py: '$0.5',
    borderRadius: '$md',
  } as const,
  previewHeaderTagText: {
    fontSize: '$xs',
    fontWeight: '$bold',
  } as const,
  previewHeaderTitle: {
    fontSize: '$lg',
    fontWeight: '$bold',
    color: '$textPrimary',
  } as const,
  linkedOfferingLabel: {
    fontSize: '$xs',
    color: '$blue500',
  } as const,
  linkedOfferingValue: {
    fontSize: '$sm',
    fontWeight: '$bold',
    color: '$blue800',
  } as const,
};