import { SHADOW_STYLES } from "@constants/STYLE_CONSTANTS";

export const loginStyles = {
  imageSpinLogo: {
    marginBottom: 16,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    left: 900,
    top: -130,
    opacity: 0.2,
  },
  imageSpinLogoLeft: {
    marginBottom: 16,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    left: -126,
    bottom: 86,
    opacity: 0.2,
  },
  imageLogo500: {
    width: 500,
    height: 500,
  },
  imageLogo500Left: {
    width: 675,
    height: 675,
  },
  languageSelector: {
    mb: '$8',
    rounded: '$full',
    bg: '$backgroundLight100',
    fontSize: '$sm',
    color: '$textDark800',
    px: '$4',
    py: '$2',
  },
  scrollView: {
    contentContainerStyle: { flexGrow: 1 },
  },
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    p: '$4',
  },
  box: {
    bg: '$white',
    px:"$6",
    pb:"$8",
    pt:"$6",
    borderRadius: '$2xl',
    shadowColor: '$gray400',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    w: '$full',
    maxWidth: 448
  },
  containerBoxShadow: SHADOW_STYLES.loginContainerBoxShadow,
  vstack: { space: 'lg', alignItems: 'center' },
  imageLogo: { w: '80px', h: '90px', mb: '$2', resizeMode: 'contain' },
  box2: {
    w: '$full',
    h: '$full',
    bg: '$rose600',
    borderRadius: '$md',
    justifyContent: 'center',
    alignItems: 'center',
  },
  text: { fontSize: '$2xl', fontWeight: '$bold', color: '$white' },
  heading: { size: 'md', color: '$primary500', textAlign: 'center', fontWeight: '$normal' },
  vstack2: { space: 'xs', alignItems: 'center', mb: '$4' },
  text2: { fontSize: '$sm', fontWeight: '$normal', color: '$primary500' },
  text3: { fontSize: '$sm', color: '$textDark400' },
  vstack3: { space: 'xs', w: '$full' },
  vstack6: { space: 'xs', w: '$full', alignItems: 'flex-start' },
  text4: { fontSize: '$sm', fontWeight: '$medium', color: '$textDark800' },
  vstack4: { space: 'xs', w: '$full' },
  text5: { fontSize: '$sm', fontWeight: '$medium', color: '$textDark800' },
  hstack: { w: '$full', space: 'sm', alignItems: 'center' },
  hstack2: { w: '$full', space: 'sm', alignItems: 'center', justifyContent: 'center' },
  errorBox: { w: '$full', bg: '$red50', p: '$3', borderRadius: '$md' },
  errorText: { fontSize: '$sm', color: '$red600' },
  button: { size: 'lg', w: '$full', variant: 'solid', action: 'primary' },
  buttonText: { color: '$white', fontWeight: '$semibold', fontSize: '$sm' },
  adminLinkText: { color: '$primary500', fontSize: '$md', fontWeight: '$medium', textDecorationLine: 'underline' },
  vstack5: { space: 'xs', mt: '$4', alignItems: 'center' },
  text6: { fontSize: '$xs', color: '$textDark500', textAlign: 'center' },
  text6ForgotPassword: { fontSize: '$sm', color: '$textDark600', textAlign: 'left' },
  text7: { fontSize: '$xs', color: '$textDark500' },
  text8: { fontSize: '$md', color: '$textDark800'},
  eyeIconButton: {position: 'absolute', right: 12, top: '50%', transform: [{ translateY: -12 }], padding: 4, zIndex: 1},
} as const;
