export const sessionsSupportStyles = {
  container: {
    flex: 1,
  },
  pageHeaderCss: {
    zIndex: 10,
    position: 'relative' as const,
  },
  headerTitleHStack: {
    alignItems: 'center',
    space: 'sm',
  },
  headerTitleText: {
    fontSize: '$2xl',
    lineHeight: '$2xl',
    fontWeight: '600',
    color: '$textForeground',
  },
  rightSectionBox: {
    position: 'relative',
    zIndex: 100,
  },
  rightSectionHStack: {
    space: 'md',
    alignItems: 'center',
  },
  createSessionBtn: {
    variant: 'outline' as const,
    bg: '$white',
    borderColor: '$borderColor',
    px: '$4',
    py: '$2.5',
    borderRadius: '$lg',
  },
  createSessionBtnText: {
    color: '$textForegroundColor',
    fontWeight: '$medium',
    fontSize: '$sm',
  },
  requestSupportBtn: {
    variant: 'solid' as const,
    bg: '#8B2842',
    px: '$4',
    py: '$2.5',
    borderRadius: '$lg',
  },
  requestSupportBtnText: {
    color: '$white',
    fontWeight: '$medium',
    fontSize: '$sm',
  },
  backdropPressable: {
    position: 'absolute' as any,
    top: -500,
    left: -1000,
    right: -1000,
    bottom: -1000,
    zIndex: 90,
  },
  dropdownBox: {
    position: 'absolute',
    top: '100%',
    right: 0,
    mt: '$2',
    width: 230,
    bg: '$white',
    borderRadius: '$xl',
    borderWidth: 1,
    borderColor: '$borderLight200',
    shadowColor: '$shadowColor',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 6,
    zIndex: 100,
    overflow: 'hidden',
  },
  dropdownItemPressable: {
    px: '$3.5',
    py: '$3',
    $hover: { bg: '$accent100' },
    $active: { bg: '$primary50' },
  },
  dropdownItemHStack: {
    space: 'sm',
    alignItems: 'flex-start',
  },
  dropdownItemIconBox: {
    mt: '$0.5',
  },
  dropdownItemVStack: {
    space: 'xs',
    flex: 1,
  },
  dropdownItemTitle: {
    fontSize: '$sm',
    fontWeight: '600',
    color: '#1E293B',
  },
  dropdownItemDescription: {
    fontSize: '$xs',
    color: '#64748B',
    lineHeight: '$xs',
  },
  contentContainer: {
    py: '$6',
  },
  contentVStack: {
    space: 'md',
  },
  comingSoonText: {
    fontSize: '$sm',
    color: '$textSecondary',
  },
  headerBadgeBox: {
    bg: '#FEE2E2',
    px: '$2.5',
    py: '$0.5',
    borderRadius: '$full',
  },
  headerBadgeText: {
    fontSize: '$xs',
    fontWeight: '500',
    color: '#8B2842',
  },
  headerSubTitleText: {
    fontSize: '$xl',
    fontWeight: '600',
    color: '$textForeground',
  },
  requestorFilterContainer: {
    bg: '$white' as const,
    borderWidth: 1,
    borderColor: '$borderLight200' as const,
    borderRadius: 16,
    p: '$3' as const,
    width: '$full' as const,
    shadowColor: '$black' as const,
    shadowOffset: { width: 0, height: 4 } as const,
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 2,
    gap: '$2' as const,
  },
  requestorFilterSearch: {},
  requestorFilterRow: {
    height: 1,
    // bg: '$borderLight200' as const,
    width: '$full' as const,
  },
  requestorFilterButton: {
    mt: 0,
    p: '$1 !important',
    bg: 'transparent' as const,
    borderWidth: 0,
    shadowColor: 'transparent' as const,
    elevation: 0,
    width: '$full' as const,
  },
  requestorFilterInput: {
    variant: 'outline' as const,
    size: 'sm' as const,
    borderRadius: '$lg' as const,
    bg: '$white' as const,
    borderColor: '$borderLight300' as const,
    height: '$9' as const,
  },
  requestorFooter: {
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
    alignItems: 'center' as const,
    width: '100%' as const,
    borderTopWidth: 1,
    borderTopColor: '$borderColor',
    paddingTop: '$2' as any,
  },
  requestorFooterText: {
    fontSize: '$xs' as const,
    color: '$textSecondary' as const,
    fontWeight: '$normal' as const,
    flex: 1,
  },
  requestorFooterOrgText: {
    fontSize: '$xs' as const,
    color: '$textPrimary' as const,
    fontWeight: '$normal' as const,
  },
  requestorFooterProvinceText: {
    fontSize: '$xs' as const,
    color: '$textSecondary' as const,
    fontWeight: '$normal' as const,
  },
  requestorFooterActions: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    columnGap: 12,
    rowGap: 12,
  },
  requestorFooterViewDetailsButton: {
    height: 32 as const,
    minHeight: 32 as const,
    paddingLeft: 12 as const,
    paddingRight: 12 as const,
    borderRadius: 10 as const,
    borderWidth: 1 as const,
    borderColor: '$borderColor' as const,
    bg: 'transparent' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    sx: {
      ':hover': { bg: '$hoverBackground' } as const,
      ':active': { bg: '$hoverBackground' } as const,
    },
  },
  requestorFooterViewDetailsText: {
    fontSize: '$xs !important' as const,
    lineHeight: 14 as const,
    fontWeight: '$semibold' as const,
    color: '$textPrimary' as const,
  },
  requestorFooterAssignButton: {
    height: 32 as const,
    minHeight: 32 as const,
    paddingLeft: 12 as const,
    paddingRight: 12 as const,
    paddingTop: 0 as const,
    paddingBottom: 0 as const,
    borderRadius: 10 as const,
    bg: '$primary500' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    gap: '$1.5' as const,
    sx: {
      ':hover': { opacity: 0.9 } as const,
      ':active': { opacity: 0.9 } as const,
    },
  },
  requestorFooterAssignText: {
    fontSize: '$xs !important' as const,
    lineHeight: 14 as const,
    fontWeight: '$semibold' as const,
    color: '$white' as const,
  },
  sessionsFoundText: {
    fontSize: '$sm',
    color: '$textSecondary',
    fontWeight: '$medium',
    marginTop: '$2',
    marginBottom: '$1',
    marginLeft: '$2'
  },
  sessionSupportSubTabBarBox: {
    bg: 'transparent',
  } as const,
  subTabBarBorderWrapper: {
    borderBottomWidth: 1,
    borderBottomColor: '$borderLight100',
    width: '100%',
  } as const,
  subTabButtonContainer: {
    paddingTop: 8,
    paddingBottom: 8,
    paddingLeft: 16,
    paddingRight: 16,
  } as const,
  emptyStateContainer: {
    borderWidth: 1,
    borderColor: '$borderLight200',
    borderRadius: 16,
    py: '$10',
    px: '$4',
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    bg: '$white',
  },
  emptyStateVStack: {
    alignItems: 'center' as const,
    space: 'md' as const,
  },
  emptyStateIconContainer: {
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    w: '$12',
    h: '$12',
  },
  emptyStateTitle: {
    fontSize: '$md',
    fontWeight: '$semibold' as const,
    color: '$textPrimary',
    textAlign: 'center' as const,
  },
  emptyStateDescription: {
    fontSize: '$sm',
    color: '$textSecondary',
    textAlign: 'center' as const,
  },
  // AssignParticipantsModal styles
  assignParticipantsFooterContainer: {
    space: 'md' as const,
    justifyContent: 'flex-end' as const,
    width: '100%' as const,
  },
  assignParticipantsCancelButton: {
    variant: 'outline' as const,
    borderColor: '$borderColor',
    bg: '$white',
    borderRadius: '$lg',
    px: '$5',
    py: '$2.5',
  },
  assignParticipantsCancelButtonText: {
    color: '$textForegroundColor',
    fontSize: '$sm',
    fontWeight: '$semibold',
  },
  assignParticipantsConfirmButton: {
    bg: '$primary500',
    borderRadius: '$lg',
    px: '$5',
    py: '$2.5',
  },
  assignParticipantsConfirmButtonText: {
    color: '$white',
    fontSize: '$sm',
    fontWeight: '$semibold',
  },
  assignParticipantsModalBodyProps: {
    flex: 1,
    overflow: 'hidden' as const,
  },
  assignParticipantsContentVStack: {
    space: 'md' as const,
    width: '100%' as const,
  },
  assignParticipantsSearchInput: {
    variant: 'outline' as const,
    size: 'md' as const,
    borderColor: '$borderColor',
    borderRadius: 10,
    bg: '$white',
    alignItems: 'center' as const,
    px: '$3',
    mb: '$2',
  },
  assignParticipantsCountHeaderHStack: {
    justifyContent: 'space-between' as const,
    alignItems: 'center' as const,
    px: '$1',
  },
  assignParticipantsCountLeftHStack: {
    alignItems: 'center' as const,
    space: 'xs' as const,
  },
  assignParticipantsCountLeftText: {
    fontSize: '$sm',
    fontWeight: '$semibold',
    color: '$textMuted',
  },
  assignParticipantsCountRightHStack: {
    alignItems: 'center' as const,
    space: 'sm' as const,
  },
  assignParticipantsCountRightText: {
    fontSize: '$sm',
    fontWeight: '$semibold',
    color: '$textMuted',
  },
  assignParticipantsClearAllText: {
    fontSize: '$sm',
    fontWeight: '$semibold',
    color: '$primary500',
  },
  assignParticipantsFlatList: {
    maxHeight: 320,
    width: '100%' as const,
  },
  assignParticipantsFlatListContent: {
    paddingBottom: 16,
  },
  assignParticipantsCard: {
    borderWidth: 1,
    borderRadius: '$xl',
    p: '$3.5',
    bg: '$white',
  },
  assignParticipantsCardStyle: {
    marginBottom: 8,
  },
  assignParticipantsCheckboxBase: {
    width: 20,
    height: 20,
    borderRadius: 9999,
    borderWidth: 2,
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
  },
  assignParticipantsAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    bg: '$backgroundLight100',
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
  },
  assignParticipantsAvatarText: {
    fontSize: '$xs',
    fontWeight: '$bold' as const,
    color: '$textPrimary',
  },
  assignParticipantsInfoVStack: {
    flex: 1,
    space: 'xs' as const,
  },
  assignParticipantsNameText: {
    fontSize: '$sm',
    fontWeight: '$semibold',
    color: '$textPrimary',
  },
  assignParticipantsMetaHStack: {
    alignItems: 'center' as const,
    space: 'xs' as const,
  },
  assignParticipantsMetaText: {
    fontSize: '$xs',
    color: '$textSecondary',
  },
  assignParticipantsBadge: {
    borderWidth: 1,
    borderRadius: '$full',
    px: '$2',
    py: '$0.5',
  },
  assignParticipantsBadgeText: {
    fontSize: '$xs',
    fontWeight: '$medium',
  },
  assignParticipantsLoadingContainer: {
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
    py: '$10',
    width: '100%' as const,
  },
  assignParticipantsEmptyContainer: {
    py: '$10',
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    px: '$6',
  },
  assignParticipantsEmptyText: {
    mt: '$3',
    fontSize: '$sm',
    fontWeight: '$medium',
    color: '$textMutedForeground',
    textAlign: 'center' as const,
  },
  assignParticipantsFooterLoadingContainer: {
    py: '$4',
    alignItems: 'center' as const,
  },
} as const;

export default sessionsSupportStyles;
