export const sessionsSupportStyles = {
  container: {
    flex: 1,
  },
  pageHeaderCss: {
    zIndex: 10,
    position: 'relative' as const,
  },
  headerTitleHStack: {
    alignItems: 'center',
    space: 'sm',
  },
  headerTitleText: {
    fontSize: '$2xl',
    lineHeight: '$2xl',
    fontWeight: '600',
    color: '$textForeground',
  },
  rightSectionBox: {
    position: 'relative',
    zIndex: 100,
  },
  rightSectionHStack: {
    space: 'md',
    alignItems: 'center',
  },
  createSessionBtn: {
    variant: 'outline' as const,
    bg: '$white',
    borderColor: '$borderColor',
    px: '$4',
    py: '$2.5',
    borderRadius: '$lg',
  },
  createSessionBtnText: {
    color: '$textForegroundColor',
    fontWeight: '$medium',
    fontSize: '$sm',
  },
  requestSupportBtn: {
    variant: 'solid' as const,
    bg: '#8B2842',
    px: '$4',
    py: '$2.5',
    borderRadius: '$lg',
  },
  requestSupportBtnText: {
    color: '$white',
    fontWeight: '$medium',
    fontSize: '$sm',
  },
  backdropPressable: {
    position: 'absolute' as any,
    top: -500,
    left: -1000,
    right: -1000,
    bottom: -1000,
    zIndex: 90,
  },
  dropdownBox: {
    position: 'absolute',
    top: '100%',
    right: 0,
    mt: '$2',
    width: 230,
    bg: '$white',
    borderRadius: '$xl',
    borderWidth: 1,
    borderColor: '$borderLight200',
    shadowColor: '$shadowColor',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 6,
    zIndex: 100,
    overflow: 'hidden',
  },
  dropdownItemPressable: {
    px: '$3.5',
    py: '$3',
    $hover: { bg: '$accent100' },
    $active: { bg: '$primary50' },
  },
  dropdownItemHStack: {
    space: 'sm',
    alignItems: 'flex-start',
  },
  dropdownItemIconBox: {
    mt: '$0.5',
  },
  dropdownItemVStack: {
    space: 'xs',
    flex: 1,
  },
  dropdownItemTitle: {
    fontSize: '$sm',
    fontWeight: '600',
    color: '#1E293B',
  },
  dropdownItemDescription: {
    fontSize: '$xs',
    color: '#64748B',
    lineHeight: '$xs',
  },
  contentContainer: {
    py: '$6',
  },
  contentVStack: {
    space: 'md',
  },
  comingSoonText: {
    fontSize: '$sm',
    color: '$textSecondary',
  },
  headerBadgeBox: {
    bg: '#FEE2E2',
    px: '$2.5',
    py: '$0.5',
    borderRadius: '$full',
  },
  headerBadgeText: {
    fontSize: '$xs',
    fontWeight: '500',
    color: '#8B2842',
  },
  headerSubTitleText: {
    fontSize: '$xl',
    fontWeight: '600',
    color: '$textForeground',
  },
  requestorFilterContainer: {
    bg: '$white' as const,
    borderWidth: 1,
    borderColor: '$borderLight200' as const,
    borderRadius: 16,
    p: '$3' as const,
    width: '$full' as const,
    shadowColor: '$black' as const,
    shadowOffset: { width: 0, height: 4 } as const,
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 2,
    gap: '$2' as const,
  },
  requestorFilterSearch: {},
  requestorFilterRow: {
    height: 1,
    // bg: '$borderLight200' as const,
    width: '$full' as const,
  },
  requestorFilterButton: {
    mt: 0,
    p: '$1 !important',
    bg: 'transparent' as const,
    borderWidth: 0,
    shadowColor: 'transparent' as const,
    elevation: 0,
    width: '$full' as const,
  },
  requestorFilterInput: {
    variant: 'outline' as const,
    size: 'sm' as const,
    borderRadius: '$lg' as const,
    bg: '$white' as const,
    borderColor: '$borderLight300' as const,
    height: '$9' as const,
  },
  requestorFooter: {
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
    alignItems: 'center' as const,
    width: '100%' as const,
    marginTop: '$2' as const,
  },
  requestorFooterText: {
    fontSize: '$xs' as const,
    color: '$textSecondary' as const,
    fontWeight: '$normal' as const,
    flex: 1,
  },
  requestorFooterOrgText: {
    fontSize: '$xs' as const,
    color: '$textPrimary' as const,
    fontWeight: '$normal' as const,
  },
  requestorFooterProvinceText: {
    fontSize: '$xs' as const,
    color: '$textSecondary' as const,
    fontWeight: '$normal' as const,
  },
  requestorFooterActions: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    columnGap: 12,
    rowGap: 12,
  },
  requestorFooterViewDetailsButton: {
    height: 32 as const,
    minHeight: 32 as const,
    paddingLeft: 12 as const,
    paddingRight: 12 as const,
    borderRadius: 10 as const,
    borderWidth: 1 as const,
    borderColor: '$borderColor' as const,
    bg: 'transparent' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    sx: {
      ':hover': { bg: '$hoverBackground' } as const,
      ':active': { bg: '$hoverBackground' } as const,
    },
  },
  requestorFooterViewDetailsText: {
    fontSize: '$xs !important' as const,
    lineHeight: 14 as const,
    fontWeight: '$semibold' as const,
    color: '$textPrimary' as const,
  },
  requestorFooterAssignButton: {
    height: 32 as const,
    minHeight: 32 as const,
    paddingLeft: 12 as const,
    paddingRight: 12 as const,
    paddingTop: 0 as const,
    paddingBottom: 0 as const,
    borderRadius: 10 as const,
    bg: '$primary500' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    gap: '$1.5' as const,
    sx: {
      ':hover': { opacity: 0.9 } as const,
      ':active': { opacity: 0.9 } as const,
    },
  },
  requestorFooterAssignText: {
    fontSize: '$xs !important' as const,
    lineHeight: 14 as const,
    fontWeight: '$semibold' as const,
    color: '$white' as const,
  },
} as const;

export default sessionsSupportStyles;
