export default {
  container: {
    px: '$4',
    py: '$6',
    '$md-px': '$6',
    pb: '$12',
  },
  cardDashboardWrapper: {
    bg: '$white',
    borderRadius: 16,
    p: 24,
    borderWidth: 1,
    borderColor: '#FEE2E2', // light reddish/pink border matching reference
    shadowColor: '$black',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.03,
    shadowRadius: 3,
    elevation: 1,
  } as const,
  sectionTitle: {
    color: '#1F2937',
    fontWeight: '700',
    fontSize: 18,
  },
  sectionSubTitle: {
    fontSize: 14,
    color: '#6B7280',
    mt: 2,
  },
  kpiCardContainer: {
    bg: '$white',
    p: '$2',
  },
  kpiDividerRight: {
    borderRightWidth: 1,
    borderRightColor: '#F3F4F6',
    pr: '$4',
  },
  iconCircleOrange: {
    width: 38,
    height: 38,
    borderRadius: 12,
    bg: '#FFEDD5',
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconCircleBlue: {
    width: 38,
    height: 38,
    borderRadius: 12,
    bg: '#DBEAFE',
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconCircleGreen: {
    width: 38,
    height: 38,
    borderRadius: 12,
    bg: '#DCFCE7',
    alignItems: 'center',
    justifyContent: 'center',
  },
  kpiHeaderOrange: {
    fontSize: 13,
    fontWeight: '700',
    color: '#C2410C',
    letterSpacing: 0.5,
  },
  kpiHeaderBlue: {
    fontSize: 13,
    fontWeight: '700',
    color: '#2563EB',
    letterSpacing: 0.5,
  },
  kpiHeaderGreen: {
    fontSize: 13,
    fontWeight: '700',
    color: '#16A34A',
    letterSpacing: 0.5,
  },
  kpiSubHeader: {
    fontSize: 13,
    color: '#6B7280',
  },
  kpiValueLarge: {
    fontSize: 38,
    fontWeight: '800',
    color: '#111827',
    lineHeight: 44,
  },
  kpiUnitText: {
    fontSize: 15,
    color: '#4B5563',
    fontWeight: '500',
  },
  kpiMetaText: {
    fontSize: 14,
    color: '#4B5563',
    mb: 4,
  },
  kpiValueBoldText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#111827',
  },
  kpiValueBlueBoldText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#2563EB',
  },
  kpiValueGreenBoldText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#16A34A',
  },
  progressBarTrack: {
    height: 6,
    borderRadius: 3,
    bg: '#EFF6FF',
    overflow: 'hidden',
    width: '100%',
  },
  progressBarOrange: {
    height: '100%',
    bg: '#EA580C',
    borderRadius: 3,
  },
  progressBarBlue: {
    height: '100%',
    bg: '#2563EB',
    borderRadius: 3,
  },
  progressBarGreen: {
    height: '100%',
    bg: '#16A34A',
    borderRadius: 3,
  },
  kpiPctTextBlue: {
    fontSize: 13,
    color: '#2563EB',
    fontWeight: '600',
  },
  kpiPctTextGreen: {
    fontSize: 13,
    color: '#16A34A',
    fontWeight: '600',
  },
  badgeGreen: {
    bg: '#DCFCE7',
    px: '$2',
    py: '$0.5',
    borderRadius: 99,
  },
  badgeGreenText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#16A34A',
  },
  badgeCount: {
    bg: '#DBEAFE',
    px: '$2',
    py: '$0.5',
    borderRadius: 99,
  },
  badgeCountText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#2563EB',
  },
  sessionCard: {
    bg: '#F8FAFC',
    p: '$3',
    borderRadius: '$lg',
    borderWidth: 1,
    borderColor: '#F1F5F9',
  },
  sessionTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1E293B',
    mb: '$1',
  },
  sessionMeta: {
    fontSize: 12,
    color: '#64748B',
  },
  viewAllBtn: {
    variant: 'link',
    bg: 'transparent',
    alignSelf: 'flex-start',
    p: '$0',
  },
  viewAllBtnText: {
    color: '#2563EB',
    fontSize: 14,
    fontWeight: '600',
  },
};